# word list for various difficulty level
easy_word_dictionary = {
"cat": "Has whiskers",  
"man": "A living being", 
"boy": "A youngster ", 
"toy": "A plaything", 
"fix": "Not spoilt anymore", 
"lie": "Not the truth", 
"coy": "Tricky", 
"tie": "Knotted", 
"tye": "... and dye", 
"cue": "A signal",
"and": "A conjunction",
"own": "Just yours",
"are": "Usually followed by 'you' in a question",
"fly": "Superman can? ",
"odd": "Not normal",
"ape": "A supposed ancestor of man",
"fry": "A style of cooking",
"our": "A collective term for 'me and you'",
"ace": "A playing card",
"for": "Sounds like 4",
"pet": "An animal companion",
"act": "A show",
"got": "Have something",
"pat": "A light tapping",
"ask": "... a question",
"get": "Obtain something",
"peg": "Used in laundry",
"arm": "A part of the body",
"god": "A supreme being",
"paw": "A part of an animal's body",
"age": "How old a thing is",
"gel": "A jelly",
"pup": "A young animal",
"ago": "When it's been a while",
"gas": "Like air",
"pit": "Hole in the ground",
"air": "Cannot been seen but neccessary for life",
"hat": "Worn on the head",
"put": "Add something into another",
"ate": "Related to consuming food" ,
"hit": "Strike something or someone",
"pot": "Used for cooking",
"all": "Everything",
"has": "To have something that was previously obtained",
"pop": "It's a genre of music",
"but": "Used when the following sentence is contraditory",
"had": "To have something before",
"pin": "Usually a stationary",
"bye": "... see you later!",
"how": "Used to ask a question"}

medium_word_list = [
"About",
"Alert"	,
"Above",
"Alike",
"Abuse",
"Alone",
"Admit",
"Alarm"	,
"Apply",
"Buyer"	,
"Chose"	,
"Craft",
"Bound"	,
"Civil"	,
"Crash",
"Brain"	,
"Carry"	,
"Claim"	,
"Cream",
"Brand"	,
"Catch"	,
"Class"	,
"Crime",
"Bread"	,
"Cause"	,
"Clean"	,
"Cross",
"Break"	,
"Chain"	,
"Guard",
"Event",
"Found",
"Guess",
"Doubt",
"Every",
"Frame",
"Guest",
"Dozen",
"Exact",
"Frank",
"Guide",
"Draft",
"Exist",
"Fraud",
"Happy",
"Drama",
"Extra",
"Fresh",
"Harry",
"Early",
"First",
"Grace",
"Image",
"Earth",
"Fixed",
"Grade",
"Index",
"Enter"	,
"Force",
"Gross",
"Joint",
"Judge",
"Metal",
"Media",
"Newly",
"Known",
"Local"	,
"Might",
"Noise",
"Label",
"Logic",
"Minor",
"North",
"Large"	,
"Loose"	,
"Minus"	,
"Noted",
"Reach"	,
"Scene",
"Pilot"	,
"Prior"	,
"Ready"	,
"Scope",
"Solve"	,
"Story"	,
"Undue",
"Sorry"	,
"Strip"	,
"Three"	,
"Union",
"Sound"	,
"Stuck"	,
"Threw"	,
"Unity",
"South"	,
"Study"	,
"Throw"	,
"Until",
"Space"	,
"Stuff"	,
"Tight"	,
"Upper",
"Upset"	,
"Whole"	,
"Waste"	,
"Wound",
"Urban"	,
"Whose"	,
"Watch"	,
"Write",
"Usage"	,
"Woman"	,
"Water"	,
"Wrong",
"Usual"	,
"Train"	,
"Wheel"	,
"Wrote",
"Valid"	,
"World"	,
"Where"	,
"Yield",
"Value"	,
"Worry"	,
"Which"	,
"Young"]

hard_word_list = [
"Ability",
"Besides",	
"Central",
"Airline",	
"Between",	
"Centric",
"Airport",	
"Billion",
"Century",
"Brother",	
"Chamber",
"Already",	
"Brought",	
"Channel",
"Another",
"Charlie",
"Anxiety",	
"Decline",	
"Charter",
"Anxious",	
"Default",	
"Anybody",	
"Defence",	
"Chicken",
"Applied",	
"Deficit",	
"Chronic",
"Arrange",
"Deliver",	
"Circuit",
"Arrival",
"Density",
"Classes",
"Article",	
"Deposit",	
"Classic",
"Assault",
"Desktop",
"Climate",
"Assured",	
"Destroy",	
"Closure",
"Attempt",
"Develop",
"Clothes",
"Attract",	
"Collect",
"Auction",
"Diamond",	
"College",
"Average",	
"Digital",
"Combine",
"Eastern",
"Discuss",	
"Comfort",
"Economy",	
"Disease",	
"Command",
"Edition",
"Display",	
"Comment",
"Elderly",	
"Dispute",	
"Compact",
"Element",
"Distant",	
"Company",
"Engaged",
"Diverse",	
"Compare",
"Enhance",	
"Divided",	
"Compete",
"Evident",
"Dynamic",
"Concern",
"Exactly",	
"Factory",	
"Concert",
"Examine",
"Faculty",	
"Conduct",
"Excited",	
"Failure",
"Connect",
"Exclude",
"Fashion",	
"Consent",
"Exhibit",
"Feature",	
"Consist",
"Expense",	
"Federal",	
"Contact",
"Explore",	
"Fiction",
"Content",
"Express",	
"Fifteen",	
"Contest",
"Gallery",
"Finance",	
"Control",
"Himself",	
"Improve",
"Justify",
"Library",	
"Notable",	
"Message",
"Nowhere",	
"Mineral",
"Obvious",
"Package",
"Mission",
"Offence",
"Mistake",
"Project",	
"Pension",	
"Present",
"Qualify",	
"Product",
"Quality",
"Popular",	
"Profile",
"Quarter",	
"Section",
"Success",
"Radical",
"Segment",	
"Suggest",
"Railway",	
"Serious",	
"Summary",
"Readily",
"Service",	
"Support",
"Warrant",
"Without",	
"Various",
"Website",	
"Written",	
"Veteran",
"Welcome",	
"Whereby",	
"Village",
"Welfare",
"Virtual",
"Violent"
]